# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:11
from __future__ import unicode_literals

import backend.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=32, unique=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('file', models.ImageField(upload_to=backend.utils.photo_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
